# Generated by Django 5.2.5 on 2025-08-22 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doubts', '0004_lesson_question_alter_doubt_user_chatsession_lesson_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Progress',
        ),
    ]
